openapi: 3.0.0
info:
  title: kns-calculator API Gateway
  version: 1.0.0
  description: Маршрутизация всех путей в YC Function kns-calculator-api

paths:
  /{proxy+}:
    x-yc-apigateway-any-method:
      summary: Catch-all proxy в FastAPI
      parameters:
        - in: path
          name: proxy
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4echfb1ckrlkv68vog5
        service_account_id: ajeur7e0n1k1n458t79n
      responses:
        default:
          description: Proxied response

  /:
    get:
      summary: Root info
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4echfb1ckrlkv68vog5
        service_account_id: ajeur7e0n1k1n458t79n
      responses:
        default:
          description: Root response
